name: Build developer image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"] 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Actions Cleaner
      uses: rse-ops/actions-cleaner/ubuntu@main
    - name: Build the Docker image
      run: docker build . --file developer/Dockerfile --tag developer:$(date +%s)
